# --------------------------
# Headless Service for Config Servers
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: configsvr-svc
  labels:
    app: configsvr
spec:
  clusterIP: None
  selector:
    app: configsvr
  ports:
    - port: 27017
      name: mongodb

---
# StatefulSet for Config Servers (replica set: configRepl)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: configsvr
spec:
  serviceName: configsvr-svc
  replicas: 3
  selector:
    matchLabels:
      app: configsvr
  template:
    metadata:
      labels:
        app: configsvr
    spec:
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "configRepl"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--configsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
      # Uncomment/modify according to your cluster
      storageClassName: local-path

---
# Headless Service for Shard1
apiVersion: v1
kind: Service
metadata:
  name: shard1-svc
  labels:
    app: shard1
spec:
  clusterIP: None
  selector:
    app: shard1
  ports:
    - port: 27017
      name: mongodb

---
# StatefulSet for Shard1 (replica set: shard1)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard1
spec:
  serviceName: shard1-svc
  replicas: 3
  selector:
    matchLabels:
      app: shard1
  template:
    metadata:
      labels:
        app: shard1
    spec:
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "shard1"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--shardsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path

---
# Headless Service for Shard2
apiVersion: v1
kind: Service
metadata:
  name: shard2-svc
  labels:
    app: shard2
spec:
  clusterIP: None
  selector:
    app: shard2
  ports:
    - port: 27017
      name: mongodb

---
# StatefulSet for Shard2 (replica set: shard2)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard2
spec:
  serviceName: shard2-svc
  replicas: 3
  selector:
    matchLabels:
      app: shard2
  template:
    metadata:
      labels:
        app: shard2
    spec:
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "shard2"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--shardsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path

---
# Service for mongos
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  selector:
    app: mongos
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

---
# Deployment for mongos (router)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:6.0
        command:
          - mongos
          - "--configdb"
          - "configRepl/configsvr-0.configsvr-svc.default.svc.cluster.local:27017,configsvr-1.configsvr-svc.default.svc.cluster.local:27017,configsvr-2.configsvr-svc.default.svc.cluster.local:27017"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017
