# =========================
# Config Servers (ReplicaSet: configRepl)
# =========================
apiVersion: v1
kind: Service
metadata:
  name: configsvr-svc
  labels:
    app: configsvr
spec:
  clusterIP: None
  selector:
    app: configsvr
  ports:
    - port: 27017
      name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: configsvr
spec:
  serviceName: configsvr-svc
  replicas: 3
  selector:
    matchLabels:
      app: configsvr
  template:
    metadata:
      labels:
        app: configsvr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "configRepl"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--configsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

# =========================
# Shard 1 (ReplicaSet: shard1)
# =========================
---
apiVersion: v1
kind: Service
metadata:
  name: shard1-svc
  labels:
    app: shard1
spec:
  clusterIP: None
  selector:
    app: shard1
  ports:
    - port: 27017
      name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard1
spec:
  serviceName: shard1-svc
  replicas: 3
  selector:
    matchLabels:
      app: shard1
  template:
    metadata:
      labels:
        app: shard1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "shard1"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--shardsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

# =========================
# Shard 2 (ReplicaSet: shard2)
# =========================
---
apiVersion: v1
kind: Service
metadata:
  name: shard2-svc
  labels:
    app: shard2
spec:
  clusterIP: None
  selector:
    app: shard2
  ports:
    - port: 27017
      name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shard2
spec:
  serviceName: shard2-svc
  replicas: 3
  selector:
    matchLabels:
      app: shard2
  template:
    metadata:
      labels:
        app: shard2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod
        image: mongo:6.0
        command:
          - mongod
          - "--replSet"
          - "shard2"
          - "--bind_ip_all"
          - "--port"
          - "27017"
          - "--dbpath"
          - "/data/db"
          - "--shardsvr"
        ports:
        - containerPort: 27017
          name: mongodb
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

# =========================
# Mongos Router
# =========================
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  selector:
    app: mongos
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:6.0
        command:
          - mongos
          - "--configdb"
          - "configRepl/configsvr-0.configsvr-svc.default.svc.cluster.local:27017,configsvr-1.configsvr-svc.default.svc.cluster.local:27017,configsvr-2.configsvr-svc.default.svc.cluster.local:27017"
          - "--bind_ip_all"
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
