#docker compose -f ReplicaSetMongoDB.yaml up -d
#docker compose -f ReplicaSetMongoDB.yaml down -v 
#docker exec -it mongo1 mongosh -> entriamo 
#docker exec -it mongo1 mongosh
version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
