version: '3.8'

services:
  # Config server
  config1:
    image: mongo:6.0
    container_name: config1
    command: mongod --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    ports:
      - 27100:27017

  # Shard 1
  shard1:
    image: mongo:6.0
    container_name: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    ports:
      - 27101:27018

  # Shard 2
  shard2:
    image: mongo:6.0
    container_name: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27019 --bind_ip_all
    ports:
      - 27102:27019

  # Router (mongos)
  mongos:
    image: mongo:6.0
    container_name: mongos
    command: mongos --configdb configReplSet/config1:27017 --bind_ip_all --port 27020
    ports:
      - 27020:27020
    depends_on:
      - config1
      - shard1
      - shard2
